### ISSUE TITLE
Local docker build fails

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/network-of-terms#1042] opened 2023-07-25 12:37 UTC
Building a local docker images using `docker build .` fails with the following error: 

`The command '/bin/sh -c NODE_ENV=production npm run compile --workspace $PACKAGE_DIR' returned a non-zero code: 1`

It is unclear how to set the $PACKAGE_DIR var and to what value...

**Comment by ddeboer** [comment] 2023-07-25 12:40
Duplicate of #983. Let me know if we can improve anything to make this clearer.

**Closed by ddeboer** 2023-07-25 12:40 UTC
Labels: bug

**Comment by EnnoMeijers** [comment] 2023-07-25 12:51
Ok, that is helpful! I am preparing the SWIB NoT Workshop and expect that not everybody is able or willing to install node. I would like to point them to using docker as an alternative, so they will be able to run their own modified version. Currently the documentation is a little scattered, I usually follow the packages/network-of-terms-graphql/Readme but that has no pointer to the docker-compose approach. And actually I would expect to find all relevant info start from the toplevel Readme.
